{{- if .Values.gossipKey}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-gossip-key
  labels: {{- include "consul.labels" . | nindent 4 }}
type: Opaque
data:
  gossip-key: {{ .Values.gossipKey | b64enc }}
{{- end }}
